[package]
name = "canadensis"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/canadensis"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: Presentation and aplication layers for CAN bus transport"

[dependencies]
fallible_collections = "0.1.2"
hash32 = "0.2.1"
heapless = "0.7.0"


# Local dependencies for development
[dependencies.canadensis_can]
version = "0.1.0"
path = "../canadensis_can"
[dependencies.canadensis_core]
version = "0.1.0"
path = "../canadensis_core"
[dependencies.canadensis_encoding]
version = "0.1.0"
path = "../canadensis_encoding"

[dev-dependencies]
socketcan = "1.7.0"
rand = "0.7.3"

[dev-dependencies.canadensis_data_types]
path = "../canadensis_data_types"
