[package]
name = "canadensis_can"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/canadensis_can"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: CAN and CAN FD transport layer"

[dependencies]
fallible_collections = "0.1.2"

# Use an unreleased version that supports const generics
[dependencies.heapless]
git = "https://github.com/japaric/heapless.git"
rev = "eff63f794f029ccc0ae66246d269e1e8e96b198e"

# Local dependency, change before publishing
[dependencies.canadensis_core]
version = "0.1.0"
path = "../canadensis_core"

[dependencies.canadensis_filter_config]
path = "../canadensis_filter_config"

[features]
# The can-fd feature increases the maximum frame capacity and maximum MTU from 8 to 64 bytes
can-fd = []
