[package]
name = "canadensis_can"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/canadensis_can"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: CAN and CAN FD transport layer"

[dependencies]
fallible_collections = "0.1.2"
heapless = "0.7.0"

# Local dependency, change before publishing
[dependencies.canadensis_core]
version = "0.1.0"
path = "../canadensis_core"

[dependencies.canadensis_filter_config]
path = "../canadensis_filter_config"

[features]
# The can-fd feature increases the maximum frame capacity and maximum MTU from 8 to 64 bytes
can-fd = []
# The std-debug feature requires the std library and enables debug output
std-debug = []
