[package]
name = "canadensis_can"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/canadensis_can"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: CAN and CAN FD transport layer"

[dependencies]
fallible_collections = "0.1.2"
heapless = "0.5.5"

# Local dependency, change before publishing
[dependencies.canadensis_core]
version = "0.1.0"
path = "../canadensis_core"
